---
abstract: 'PostgreSQL database support for IO::Async'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-PostgreSQL
requires:
  IO::Async: 0.36
  Protocol::PostgreSQL: 0.008
  parent: 0
version: 0.005
